### ISSUE TITLE
i will bring this up on scratch

### ISSUE THREAD

**Issue by gosoccerboy5** [somerandomdood3/annoyingforumers2#1]
if you dont reply within the next hour i will link this on scratch
what will you do
mwahahahhaa

**Comment by gosoccerboy5** [comment]
ok you had a couple minutes to spare
this time if its not within 30 minutes i will share this

**Comment by somerandomdood3** [comment]
ok

**Comment by gosoccerboy5** [comment]
you have 3 minutes

**Comment by somerandomdood3** [comment]
uh, no?

**Comment by gosoccerboy5** [comment]
I'll let you off the hook. probably a couple seconds late, but ok.

**Comment by gosoccerboy5** [comment]
1 minute

**Comment by gosoccerboy5** [comment]
this time you have one minute

**Comment by somerandomdood3** [comment]
bruh

**Comment by gosoccerboy5** [comment]
now you have 5 seconds this time

**Comment by somerandomdood3** [comment]
bruh

**Comment by gosoccerboy5** [comment]
too late

**Comment by somerandomdood3** [comment]
issue resolved

**Comment by gosoccerboy5** [comment]
no

**Comment by somerandomdood3** [comment]
please let me go
